# Generated by Django 3.0.4 on 2020-04-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='https://8-track-assets.s3.us-east-1.amazonaws.com/media/default-image.png?response-content-disposition=inline&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEKL%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCXVzLWVhc3QtMSJHMEUCIHu8DP%2Bo4Gerp8NBxgrG7O%2Fo6YqzZ7w6WX7em05tSydLAiEA%2FoA%2B4BcDsSdD9Lw2y7g%2B0C1rYHV9atdDdM5wX6FKsc4q7wEIq%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARAAGgwzNzgyODM2MDU0NDciDLCajYXoN9AKNcf1jyrDAfm%2FLy%2Fw1Sa2w8y1YG8PwU3Rz6C%2BMFiyzujR50NkNjrePYLvdyCo%2FI1iYcCn3j45QQ3KU48vJGDbiV4WXcwh3p%2B8r7tNSQoIyV0VLD1Q3MGZxIzTRVWTBec5avE8Gg9eCJmyu%2FaGI%2BgLKns%2B1FSGRjLu2Cfqc0tRmhFIJSfB09FZXbpItd%2FVO4Czu0ZvqnjifvVqL%2Bcy%2FUDrMVpTLvdXt84YMFSobiG4Ada6FI8rj6ke3EyjydpOakWSwfgJ4LCQVpZqbDCI2a30BTrwAj5t020qAVXfGEez4LdpIHKSRcteLSOBGf8byLUEUNjmIiOUzOE1RMkvSbyRixBLRI9vPaCj7fv5dMy%2FQlHOuYNkYkuBjBDajmZ6ScZAye9zPwbg4vTou%2F6Htk9i6U%2FdbLNOr7bTTj5dV7cWso0Edf%2Bt5KMhZdFZByVc%2BBeZ4YzcyHHL1gsrgS2dZW8NjB3VqWnCwRghf3PSoeIh0euurwC3gMm8L%2BIAWIIekddAc6%2FNsWdZwAz5Eo7cXAPBS8hddNstHeUcx89iwHu8Fn8cK3hBDvHVpSJ9h2cFvTkspPs%2FGpq1GIFC4qoDNtTtVmOzBq8EEatkCg5v9gwfJjtu73nX3FeVd1qof%2FXO5WFGYivoIsQblc%2BLRKiRH%2FFrWu%2FDy%2BCVYjeDQj9RM%2F%2Bxm8IeOZoT4kRalklZbnsgnxve0CesSfM8Tze3lWea8XNJMFZIOrQ95rGjadS7Gx7E1SQkHf%2BWKVVcVtTaRrOaJhI2pa2k&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20200406T180859Z&X-Amz-SignedHeaders=host&X-Amz-Expires=300&X-Amz-Credential=ASIAVQE3VXXDRJKFOGD2%2F20200406%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=71e7e5d9758956465d691284d3c50a15ddb4f3d562b9cf95369ccfcafbcaaf9c', upload_to=''),
        ),
    ]
