# Generated by Django 3.0.4 on 2020-04-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200406_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='https://8-track-assets.s3.amazonaws.com/media/default-image.png', upload_to=''),
        ),
    ]
