# Generated by Django 3.0.4 on 2020-04-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200406_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='default-image_mv5FQYX.png', upload_to=''),
        ),
    ]
