# Generated by Django 3.0.4 on 2020-03-23 16:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('artist', models.CharField(max_length=400)),
                ('genre', models.CharField(max_length=400)),
                ('track', models.CharField(max_length=400)),
                ('release_date', models.CharField(max_length=400)),
                ('added_on', models.DateField(auto_now=True)),
                ('album_cover', models.ImageField(default='default.png', upload_to='')),
                ('users', models.ManyToManyField(related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
