# Generated by Django 3.0.4 on 2020-03-31 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200327_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_uri',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
